language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=traviz CXX=g++-4.8
services:
  - mongodb

before_script:
  - sleep 15
  - mongo worklist-test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
